spring:
  datasource:
    url: jdbc:mysql://SVsrrmnZB2CKyh4576v4sAElh1XRDQ49.iptime.org:3306/demoForum?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: crud
    password: crud
  jpa:
    hibernate:
      ddl-auto: update
  boot:
    admin:
      client:
        url: 'http://svsrrmnzb2ckyh4576v4saelh1xrdq49.iptime.org:11111'
management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  header: Authorization
  secret: aGVsbG8tbXktcmVhbC1uYW1lLWlzLXdvbmp1bi10aGlzLWtleS1pcy12ZXJ5LWltcG9ydGFudC1zby1iZS1jYXJlZnVsLXRoYW5rLXlvdQ==
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000