spring:
  datasource:
    url: jdbc:mysql://SVsrrmnZB2CKyh4576v4sAElh1XRDQ49.iptime.org:3306/demoForum?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: crud
    password: crud
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.apache.coyote.http11: info