spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://SVsrrmnZB2CKyh4576v4sAElh1XRDQ49.iptime.org:3306/demoForum?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: crud
    password: crud
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.sql: debug
    org.apache.coyote.http11: debug