pipeline {
    agent any
    stages {
        stage('hello') {
            steps {
                sh 'echo hello world'
                echo("build number is ${currentBuild.number}")
            }
        }
    }
}